server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    item-service: /item/**      # 将商品微服务映射到/item/**
    search-service: /search/**  # 搜索微服务
    user-service: /user/**      # 用户微服务
    auth-service: /auth/**      # 授权中心
    cart-service: /cart/**      # 购物车
    order-service: /order/**    # 订单中心
  ignored-services:
    - upload-service # 忽略upload-service服务
  add-host-header: true   # 携带请求本身的host头信息
  sensitive-headers:      # 禁止使用的头信息，设置为null，否则set-cookie无效


ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
ly:
  jwt:
    pubKeyPath: C:/Users/dy181/Documents/RsaKey/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/check
      - /api/user/send
      - /api/user/register
      - /api/user/query
      - /api/item
      - /api/cart/list
logging:
  level:
    root: warn