server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.138.105:3306/leyou?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
#  redis:
#    host: 192.168.206.66
#  rabbitmq:
#    host: 192.168.206.66
#    username: /leyou
#    password: 123
#    virtual-host: /leyou
#    template:
#      retry:
#        enabled: true
#        initial-interval: 10000ms
#        max-interval: 300000ms
#        multiplier: 2
#      exchange: ly.item.exchange
#    publisher-confirms: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}